### ISSUE TITLE
Unlock the power of Jekyll's data files and generators

### ISSUE THREAD

**Issue by ndorfin** [starshyyne/lauramunro.nz#20]
This topic was one of the most transformative for me when using Static Site Generators. The idea goes a little something like this:

1. Place YAML / JSON or CSV files in the `_data` directory
2. Jekyll then exposes them in a handy API
3. Transform the data into in-page loops, etc.
4. Profit!

Now, it looks like you're familiar with all that, but you can take this principle a little further by using generators.

Instead of just making that data available within a page, you can use it to generate whole sections of your site.

A good working example could do something like this. Let's say you wanted to extend your site with a list of all your works, on a page-by-page basis. First, you'll need a data file:

```yaml
# in `_data/portfolio.yml`

- id: myacc
  name: My ACC
  description: |- 
     The self service product for injuried New Zealanders to access support with ACC.

     As the UX/UI Designer I am responsible for the discovery and design of new features, and provide on-going support for the development phase.
  image_url: 'MyACC.png'
  link_url: https://my.acc.co.nz/
- id: tūī
  # etc
- id: opal3
  # etc
```
[This data file could be used right away in your homepage, listing each of your work items.]

Then, you could [create the corresponding generator](https://jekyllrb.com/docs/plugins/generators/) under `_plugins` that, when given a template file, will create each of the portfolio detail pages for you!

**Now, why use this approach rather than your current posts implementation?**

Jekyll Posts are a useful way to build blog posts, in that they're supported by RSS, and possibly build up a category list, sitemap, etc.

Data files on the other hand, can be used for any repeating scenario, depending on how much time you sink into defining the generators and their templates.

**Next steps?**

Waddayathink?
